name: .NET CI/CD

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Optional: Publish the app (for deployment)
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    name: Google Cloud Run Docker CI/CD

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        wimmed: wimmed
        install_components: 'beta'

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker africa-south1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t africa-south1-docker.pkg.dev/wimmed/WimMed/Container1:${{ github.sha }} .

    - name: Push Docker image
      run: docker push africa-south1-docker.pkg.dev/wimmed/WimMed/Container1:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy <SERVICE_NAME> \
          --image africa-south1-docker.pkg.dev/wimmed/WimMed/Container1${{ github.sha }} \
          --region africa-south1 \
          --platform managed \
          --allow-unauthenticated
